version: '3'

services:
  db:
    container_name: small-shop
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_DB=${NAME_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    
    